// packages/vue/src/components/fields/MergeMenu.vue
<script setup lang="ts">
/* ═══ Merge-field picker ═══
 *
 * Emits a formatted token; the field that owns the caret decides where it lands. The menu is
 * `position: fixed` in the stylesheet and positioned from the trigger's viewport rect, so it
 * escapes the inspector's `overflow-y: auto` instead of being clipped by it. */

import { computed, onBeforeUnmount, ref, watch } from "vue";
import { useEditor, useTranslator } from "../../context";
import { UI_ICONS } from "../../icons";
import EbIcon from "../EbIcon.vue";

const emit = defineEmits<{ insert: [token: string] }>();

const editor = useEditor();
const t = useTranslator(editor);

const open = ref(false);
const search = ref("");
const anchor = ref({ top: 0, left: 0 });
const trigger = ref<HTMLButtonElement | null>(null);

const groups = computed(() => {
  const all = editor.merge?.groups() ?? [];
  const query = search.value.trim().toLowerCase();
  if (!query) return all;
  return all
    .map((group) => ({
      group: group.group,
      fields: group.fields.filter(
        (field) =>
          field.label.toLowerCase().includes(query) || field.token.toLowerCase().includes(query),
      ),
    }))
    .filter((group) => group.fields.length > 0);
});

const empty = computed(() => groups.value.length === 0);

const MENU_WIDTH = 268;
const MENU_HEIGHT = 320;

function toggle() {
  if (open.value) {
    open.value = false;
    return;
  }
  const rect = trigger.value?.getBoundingClientRect();
  if (rect) {
    /* Flip above the trigger when the menu would fall off the bottom of the window. */
    const below = rect.bottom + 6;
    const top = below + MENU_HEIGHT > window.innerHeight ? Math.max(8, rect.top - MENU_HEIGHT - 6) : below;
    anchor.value = { top, left: Math.max(8, Math.min(rect.left, window.innerWidth - MENU_WIDTH - 8)) };
  }
  search.value = "";
  open.value = true;
}

function pick(token: string) {
  emit("insert", editor.merge?.format(token) ?? token);
  open.value = false;
}

/* Any pointer press outside the menu dismisses it — a picker that needs its own trigger clicked
   again to close is the most common way one gets left hanging over the canvas. */
const onDocumentPointerDown = (event: PointerEvent) => {
  const target = event.target as Node | null;
  if (!target) return;
  if (trigger.value?.contains(target)) return;
  if ((target as Element).closest?.(".eb-merge__menu")) return;
  open.value = false;
};

const onDocumentKeyDown = (event: KeyboardEvent) => {
  if (event.key === "Escape") open.value = false;
};

watch(open, (isOpen) => {
  if (isOpen) {
    window.addEventListener("pointerdown", onDocumentPointerDown, true);
    window.addEventListener("keydown", onDocumentKeyDown);
  } else {
    window.removeEventListener("pointerdown", onDocumentPointerDown, true);
    window.removeEventListener("keydown", onDocumentKeyDown);
  }
});

onBeforeUnmount(() => {
  window.removeEventListener("pointerdown", onDocumentPointerDown, true);
  window.removeEventListener("keydown", onDocumentKeyDown);
});
</script>

<template>
  <span class="eb-merge">
    <button
      ref="trigger"
      type="button"
      class="eb-merge__trigger"
      :aria-label="t('field.insertField')"
      :aria-expanded="open"
      @click.stop="toggle"
    >
      <EbIcon :svg="UI_ICONS.merge" />
      {{ t("field.insertField") }}
    </button>

    <Teleport to="body">
      <div
        v-if="open"
        class="eb-merge__menu"
        role="dialog"
        :aria-label="t('field.insertField')"
        :style="{ top: `${anchor.top}px`, left: `${anchor.left}px` }"
      >
        <div class="eb-merge__search">
          <input
            v-model="search"
            type="search"
            class="eb-input"
            :placeholder="t('field.searchRecords')"
            :aria-label="t('field.searchRecords')"
          />
        </div>
        <div class="eb-merge__list">
          <p v-if="empty" class="eb-merge__empty">{{ t("field.noRecords") }}</p>
          <template v-for="group in groups" :key="group.group">
            <div class="eb-merge__group-title">{{ group.group }}</div>
            <button
              v-for="field in group.fields"
              :key="field.token"
              type="button"
              class="eb-merge__option"
              @click="pick(field.token)"
            >
              <span class="eb-merge__option-label">{{ field.label }}</span>
              <span class="eb-merge__option-token">{{ editor.merge?.format(field.token) }}</span>
            </button>
          </template>
        </div>
      </div>
    </Teleport>
  </span>
</template>

// packages/react/src/components/fields/MergeMenu.tsx
/* ═══ Merge-field picker ═══
 *
 * Portalled to the body and positioned from the trigger's own rect: below 1100px the inspector is
 * a `translateX`-animated sheet, and a transformed ancestor turns `position: fixed` into
 * something relative to that ancestor. */

import { useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import { useEditor, useTranslator } from "../../context";
import { MergeIcon } from "../../icons";
import { Portal } from "../Portal";

type TextControl = HTMLInputElement | HTMLTextAreaElement;

export interface MergeTriggerProps {
  /** The control the token is inserted into. */
  control: { current: TextControl | HTMLElement | null };
  value: string;
  onChange: (next: string) => void;
}

export function MergeTrigger({ control, value, onChange }: MergeTriggerProps) {
  const editor = useEditor();
  const t = useTranslator();
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [anchor, setAnchor] = useState<{ top: number; left: number } | null>(null);
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  /* Captured on open: focusing the search box destroys the caret we are meant to insert at. */
  const caret = useRef<number | null>(null);

  const openMenu = useCallback(() => {
    const node = control.current;
    caret.current = isTextControl(node) ? node.selectionStart : null;
    const rect = triggerRef.current?.getBoundingClientRect();
    if (rect) setAnchor({ top: rect.bottom + 6, left: rect.right - 268 });
    setSearch("");
    setOpen(true);
  }, [control]);

  const insert = useCallback(
    (token: string) => {
      const formatted = editor.merge?.format(token) ?? token;
      const at = caret.current;
      const next =
        at === null ? `${value}${formatted}` : `${value.slice(0, at)}${formatted}${value.slice(at)}`;
      onChange(next);
      setOpen(false);
      const node = control.current;
      if (isTextControl(node)) {
        const position = (at ?? value.length) + formatted.length;
        requestAnimationFrame(() => {
          node.focus();
          node.setSelectionRange(position, position);
        });
      }
    },
    [control, editor.merge, onChange, value],
  );

  if (!editor.merge) return null;

  return (
    <>
      <button
        type="button"
        ref={triggerRef}
        className="eb-merge__trigger"
        /* The label element around it would steal the click and focus the input instead. */
        onMouseDown={(event) => event.preventDefault()}
        onClick={openMenu}
        aria-label={t("field.insertField")}
        aria-expanded={open}
      >
        <MergeIcon />
        {t("field.insertField")}
      </button>
      {open && anchor ? (
        <MergeMenu
          anchor={anchor}
          search={search}
          onSearch={setSearch}
          onPick={insert}
          onClose={() => setOpen(false)}
        />
      ) : null}
    </>
  );
}

interface MergeMenuProps {
  anchor: { top: number; left: number };
  search: string;
  onSearch: (value: string) => void;
  onPick: (token: string) => void;
  onClose: () => void;
}

function MergeMenu({ anchor, search, onSearch, onPick, onClose }: MergeMenuProps) {
  const editor = useEditor();
  const t = useTranslator();
  const menuRef = useRef<HTMLDivElement | null>(null);
  const [position, setPosition] = useState(anchor);

  /* Nudged back inside the viewport once it has a measured height — a menu opened from a field
     near the bottom of the inspector would otherwise hang off the screen. */
  useLayoutEffect(() => {
    const node = menuRef.current;
    if (!node) return;
    const rect = node.getBoundingClientRect();
    const top = Math.min(anchor.top, Math.max(8, window.innerHeight - rect.height - 8));
    const left = Math.min(Math.max(8, anchor.left), Math.max(8, window.innerWidth - rect.width - 8));
    setPosition({ top, left });
  }, [anchor]);

  useEffect(() => {
    const onPointerDown = (event: PointerEvent) => {
      if (!menuRef.current?.contains(event.target as Node)) onClose();
    };
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        event.stopPropagation();
        onClose();
      }
    };
    window.addEventListener("pointerdown", onPointerDown, true);
    window.addEventListener("keydown", onKeyDown, true);
    return () => {
      window.removeEventListener("pointerdown", onPointerDown, true);
      window.removeEventListener("keydown", onKeyDown, true);
    };
  }, [onClose]);

  const needle = search.trim().toLowerCase();
  const groups = (editor.merge?.groups() ?? [])
    .map((group) => ({
      group: group.group,
      fields: group.fields.filter(
        (entry) =>
          !needle ||
          entry.label.toLowerCase().includes(needle) ||
          entry.token.toLowerCase().includes(needle),
      ),
    }))
    .filter((group) => group.fields.length > 0);

  return (
    <Portal>
      <div
        ref={menuRef}
        className="eb-merge__menu"
        style={{ top: position.top, left: position.left }}
        role="dialog"
        aria-label={t("field.insertField")}
      >
        <div className="eb-merge__search">
          <input
            className="eb-input"
            autoFocus
            value={search}
            placeholder={t("field.searchRecords")}
            onChange={(event) => onSearch(event.target.value)}
          />
        </div>
        <div className="eb-merge__list">
          {groups.length === 0 ? (
            <div className="eb-merge__empty">{t("field.noRecords")}</div>
          ) : (
            groups.map((group) => (
              <div key={group.group}>
                <div className="eb-merge__group-title">{group.group}</div>
                {group.fields.map((entry) => (
                  <button
                    key={entry.token}
                    type="button"
                    className="eb-merge__option"
                    onClick={() => onPick(entry.token)}
                  >
                    <span className="eb-merge__option-label">{entry.label}</span>
                    <span className="eb-merge__option-token">
                      {editor.merge?.format(entry.token) ?? entry.token}
                    </span>
                  </button>
                ))}
              </div>
            ))
          )}
        </div>
      </div>
    </Portal>
  );
}

function isTextControl(node: unknown): node is TextControl {
  return node instanceof HTMLInputElement || node instanceof HTMLTextAreaElement;
}
