// packages/vue/src/components/BuilderRow.vue
<script setup lang="ts">
/* ═══ BuilderRow ═══
 *
 * One row on the canvas matching Growtality:
 * Left floating toolbar handle:
 *  - drag_indicator grip
 *  - arrow_upward (move up)
 *  - arrow_downward (move down)
 *  - view_column (edit layout)
 *  - content_copy (duplicate)
 *  - delete (delete row)
 */

import { computed } from "vue";
import type { Row } from "@email-builder/core";
import { useEditor } from "../context";
import { useEditorSelector } from "../composables";
import { vDrag, vDrop } from "../directives";
import BuilderColumn from "./BuilderColumn.vue";

const props = defineProps<{ row: Row; index: number }>();

const editor = useEditor();

const totalRows = useEditorSelector((state) => state.document.rows.length);
const selected = useEditorSelector(
  (state) => state.selection?.kind === "row" && state.selection.id === props.row.id,
);
const landed = useEditorSelector((state) => state.landedId === props.row.id);

const classes = computed(() =>
  [
    "builder-row",
    selected.value ? "builder-row--selected" : "",
    landed.value ? "builder-row--landed" : "",
  ]
    .filter(Boolean)
    .join(" "),
);

function moveRow(dir: number) {
  const target = props.index + dir;
  if (target >= 0 && target < totalRows.value) {
    editor.moveRow(props.row.id, target);
  }
}
</script>

<template>
  <div
    v-drag="{ editor, data: { kind: 'row', rowId: row.id } }"
    v-drop="{ editor, data: { kind: 'row', rowId: row.id, index }, orientation: 'vertical' }"
    :class="classes"
    @click.stop="editor.select({ kind: 'row', id: row.id })"
  >
    <!-- Left floating toolbar -->
    <div class="builder-row__toolbar" :aria-label="`Row ${index + 1} actions`">
      <button
        type="button"
        class="builder-row__grip"
        :aria-label="`Move row ${index + 1}`"
      >
        <span class="material-symbols-outlined" aria-hidden="true">drag_indicator</span>
      </button>

      <div class="builder-row__actions">
        <button
          type="button"
          class="builder-row__action"
          aria-label="Move row up"
          :disabled="index === 0"
          title="Move row up"
          @click.stop="moveRow(-1)"
        >
          <span class="material-symbols-outlined" aria-hidden="true">arrow_upward</span>
        </button>
        <button
          type="button"
          class="builder-row__action"
          aria-label="Move row down"
          :disabled="index >= totalRows - 1"
          title="Move row down"
          @click.stop="moveRow(1)"
        >
          <span class="material-symbols-outlined" aria-hidden="true">arrow_downward</span>
        </button>
        <button
          type="button"
          class="builder-row__action"
          aria-label="Change row layout"
          title="Change row layout"
          @click.stop="editor.select({ kind: 'row', id: row.id })"
        >
          <span class="material-symbols-outlined" aria-hidden="true">view_column</span>
        </button>
        <button
          type="button"
          class="builder-row__action"
          aria-label="Duplicate row"
          title="Duplicate row"
          @click.stop="editor.duplicateRow(row.id)"
        >
          <span class="material-symbols-outlined" aria-hidden="true">content_copy</span>
        </button>
        <button
          type="button"
          class="builder-row__action builder-row__action--danger"
          aria-label="Delete row"
          title="Delete row"
          @click.stop="editor.removeRow(row.id)"
        >
          <span class="material-symbols-outlined" aria-hidden="true">delete</span>
        </button>
      </div>
    </div>

    <div class="builder-row__columns">
      <BuilderColumn
        v-for="(column, ci) in row.columns"
        :key="column.id"
        :row="row"
        :column="column"
        :column-index="ci"
      />
    </div>
  </div>
</template>

// packages/react/src/components/BuilderRow.tsx
/* ═══ BuilderRow ═══
 *
 * One row on the canvas matching Growtality:
 * Left floating toolbar handle:
 *  - drag_indicator grip
 *  - arrow_upward (move up)
 *  - arrow_downward (move down)
 *  - view_column (edit layout)
 *  - content_copy (duplicate)
 *  - delete (delete row)
 */

import { useCallback } from "react";
import type { Row } from "@email-builder/core";
import { useEditor, useTranslator } from "../context";
import { useDraggable, useDroppable } from "../hooks/useDnd";
import { useEditorSelector } from "../hooks/useEditorState";
import { BuilderColumn } from "./BuilderColumn";

export interface BuilderRowProps {
  row: Row;
  index: number;
}

export function BuilderRow({ row, index }: BuilderRowProps) {
  const editor = useEditor();
  const t = useTranslator();

  const totalRows = useEditorSelector((state) => state.document.rows.length);
  const selected = useEditorSelector(
    (state) => state.selection?.kind === "row" && state.selection.id === row.id,
  );
  const landed = useEditorSelector((state) => state.landedId === row.id);

  const drop = useDroppable(
    { kind: "row", rowId: row.id, index },
    { orientation: "vertical" },
  );
  const drag = useDraggable({ kind: "row", rowId: row.id });

  const setNode = useCallback(
    (element: HTMLDivElement | null) => {
      drop.setNode(element);
      drag.setNode(element);
    },
    [drop.setNode, drag.setNode],
  );

  const moveRow = (dir: number) => {
    const target = index + dir;
    if (target >= 0 && target < totalRows) {
      editor.moveRow(row.id, target);
    }
  };

  const classes = [
    "builder-row",
    "eb-row",
    selected ? "builder-row--selected eb-row--selected" : "",
    landed ? "builder-row--landed eb-row--landed" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      ref={setNode}
      className={classes}
      onClick={(event) => {
        event.stopPropagation();
        editor.select({ kind: "row", id: row.id });
      }}
    >
      {/* Left floating toolbar */}
      <div className="builder-row__toolbar" aria-label={`Row ${index + 1} actions`}>
        <button
          type="button"
          ref={drag.setHandle}
          className="builder-row__grip"
          aria-label={`Move row ${index + 1}`}
        >
          <span className="material-symbols-outlined" aria-hidden="true">drag_indicator</span>
        </button>

        <div className="builder-row__actions">
          <button
            type="button"
            className="builder-row__action"
            aria-label="Move row up"
            disabled={index === 0}
            title="Move row up"
            onClick={(event) => {
              event.stopPropagation();
              moveRow(-1);
            }}
          >
            <span className="material-symbols-outlined" aria-hidden="true">arrow_upward</span>
          </button>
          <button
            type="button"
            className="builder-row__action"
            aria-label="Move row down"
            disabled={index >= totalRows - 1}
            title="Move row down"
            onClick={(event) => {
              event.stopPropagation();
              moveRow(1);
            }}
          >
            <span className="material-symbols-outlined" aria-hidden="true">arrow_downward</span>
          </button>
          <button
            type="button"
            className="builder-row__action"
            aria-label="Change row layout"
            title="Change row layout"
            onClick={(event) => {
              event.stopPropagation();
              editor.select({ kind: "row", id: row.id });
            }}
          >
            <span className="material-symbols-outlined" aria-hidden="true">view_column</span>
          </button>
          <button
            type="button"
            className="builder-row__action"
            aria-label="Duplicate row"
            title="Duplicate row"
            onClick={(event) => {
              event.stopPropagation();
              editor.duplicateRow(row.id);
            }}
          >
            <span className="material-symbols-outlined" aria-hidden="true">content_copy</span>
          </button>
          <button
            type="button"
            className="builder-row__action builder-row__action--danger"
            aria-label="Delete row"
            title="Delete row"
            onClick={(event) => {
              event.stopPropagation();
              editor.removeRow(row.id);
            }}
          >
            <span className="material-symbols-outlined" aria-hidden="true">delete</span>
          </button>
        </div>
      </div>

      <div className="builder-row__columns eb-row__columns">
        {row.columns.map((column, columnIndex) => (
          <BuilderColumn
            key={column.id}
            row={row}
            column={column}
            columnIndex={columnIndex}
          />
        ))}
      </div>
    </div>
  );
}
