// packages/vue/src/components/BuilderBlock.vue
<script setup lang="ts">
/* ═══ BuilderBlock ═══
 *
 * A block on the canvas:
 * Floating action bar:
 *  - Label: Image, Heading, etc.
 *  - drag_indicator
 *  - arrow_upward
 *  - arrow_downward
 *  - content_copy
 *  - delete
 */

import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { columnWidths } from "@email-builder/core";
import type { Block, Column, MergeField, Row } from "@email-builder/core";
import { useEditor, useTranslator } from "../context";
import { useDragState, useEditorSelector } from "../composables";
import { compileBlockPreview } from "../preview";
import { vDrag, vDrop } from "../directives";
import MentionMenu from "./MentionMenu.vue";
import RichTextToolbar from "./RichTextToolbar.vue";
import { isRichTextField } from "@email-builder/engine";
import EbGlyph from "./EbGlyph.vue";
import { selectFromClick } from "@email-builder/engine";

const props = defineProps<{ block: Block; row: Row; column: Column; columnIndex: number }>();

const editor = useEditor();
const t = useTranslator(editor);

const definition = computed(() => editor.blocks.get(props.block.type));

const selected = useEditorSelector(
  (state) => state.selection?.kind === "block" && (state.selection.id === props.block.id || state.selectedIds.includes(props.block.id)),
);
const landed = useEditorSelector((state) => state.landedId === props.block.id);
const editing = useEditorSelector((state) => state.editingBlockId === props.block.id);
/* The formatting bar only makes sense for rich text; headings and labels are stored as plain text. */
const richText = computed(() => isRichTextField(definition.value, definition.value?.inlineEditKey));
const settings = useEditorSelector((state) => state.document.settings);
/* Re-render when the canvas switches Desktop/Mobile: mobile overrides change the preview. */
const device = useEditorSelector((state) => state.device);

const dragState = useDragState(editor);
const isOver = computed(() => {
  const over = dragState.value.over;
  return over?.kind === "block" && (over as any).blockId === props.block.id;
});
const edge = computed(() => {
  if (!isOver.value) return null;
  return dragState.value.indicator?.edge ?? "inside";
});

const blockIndex = computed(() =>
  props.column.blocks.findIndex((b) => b.id === props.block.id),
);
const totalBlocks = computed(() => props.column.blocks.length);

function moveBlock(dir: number) {
  const target = blockIndex.value + dir;
  if (target >= 0 && target < totalBlocks.value) {
    editor.moveBlock(props.block.id, props.column.id, target);
  }
}

const html = computed(() => {
  const widths = columnWidths(props.row, settings.value.contentWidth);
  const columnWidth = widths[props.columnIndex] ?? settings.value.contentWidth;
  const padding = props.column.style.padding;
  const width = Math.max(0, columnWidth - (padding?.left ?? 0) - (padding?.right ?? 0));
  void device.value;
  return compileBlockPreview({ editor, block: props.block, settings: settings.value, width });
});

const classes = computed(() =>
  [
    "builder-block",
    "eb-block",
    selected.value ? "builder-block--selected eb-block--selected" : "",
    landed.value ? "builder-block--landed eb-block--landed" : "",
    editing.value ? "builder-block--editing eb-block--editing" : "",
  ]
    .filter(Boolean)
    .join(" "),
);

/* ── Inline editing & @ Mention State ── */
const renderEl = ref<HTMLElement | null>(null);
const currentTarget = ref<HTMLElement | null>(null);
let inlineCleanup: (() => void) | null = null;

const mentionState = ref<{
  open: boolean;
  coords: { top: number; left: number };
  query: string;
  atIndex: number;
  textNode: Node | null;
}>({
  open: false,
  coords: { top: 0, left: 0 },
  query: "",
  atIndex: -1,
  textNode: null,
});

function onClickBlock(event: MouseEvent) {
  /* ⌘/Ctrl-click and Shift-click build a multi-selection instead of starting to edit. */
  if (selectFromClick(editor, event, { kind: "block", id: props.block.id })) return;
  if (definition.value?.inlineEditKey) {
    editor.beginInlineEdit(props.block.id);
  }
}

function checkMention(target: HTMLElement) {
  const sel = window.getSelection();
  if (!sel || !sel.rangeCount || !sel.isCollapsed) {
    if (mentionState.value.open) mentionState.value.open = false;
    return;
  }
  const range = sel.getRangeAt(0);
  const node = range.startContainer;
  if (node.nodeType !== Node.TEXT_NODE) {
    if (mentionState.value.open) mentionState.value.open = false;
    return;
  }

  const text = node.textContent ?? "";
  const offset = range.startOffset;
  const textBefore = text.slice(0, offset);
  const atIndex = textBefore.lastIndexOf("@");
  if (atIndex === -1) {
    if (mentionState.value.open) mentionState.value.open = false;
    return;
  }

  const query = textBefore.slice(atIndex + 1);
  if (/[\s\n\r]/.test(query)) {
    if (mentionState.value.open) mentionState.value.open = false;
    return;
  }

  let coords = { top: 0, left: 0 };
  try {
    const cloneRange = range.cloneRange();
    cloneRange.setStart(node, atIndex);
    cloneRange.setEnd(node, offset);
    const rect = cloneRange.getBoundingClientRect();
    if (rect && rect.top > 0) {
      coords = { top: rect.bottom, left: rect.left };
    } else {
      const tRect = target.getBoundingClientRect();
      coords = { top: tRect.bottom, left: tRect.left + 20 };
    }
  } catch {
    const tRect = target.getBoundingClientRect();
    coords = { top: tRect.bottom, left: tRect.left + 20 };
  }

  mentionState.value = {
    open: true,
    coords,
    query,
    atIndex,
    textNode: node,
  };
}

function startInline() {
  const key = definition.value?.inlineEditKey;
  if (!key || !renderEl.value) return;
  const host = renderEl.value;
  const marked = host.querySelector<HTMLElement>("[data-eb-inline]");
  const cell = host.querySelector("td");
  const first = cell?.firstElementChild;
  const target = marked ?? (first instanceof HTMLElement ? first : null);
  if (!target) {
    editor.endInlineEdit();
    return;
  }
  currentTarget.value = target;

  target.setAttribute("data-eb-inline", "");
  target.contentEditable = "true";
  if (document.activeElement !== target) {
    target.focus();
  }

  const commit = () => {
    const isHeading = props.block.type === "heading";
    const val = isHeading ? (target.innerText || target.textContent || "") : target.innerHTML;
    editor.updateContent(props.block.id, { [key]: val }, "inline");
    editor.endInlineEdit();
  };

  const onKeyDown = (e: KeyboardEvent) => {
    if (mentionState.value.open) {
      if (
        e.key === "ArrowDown" ||
        e.key === "ArrowUp" ||
        e.key === "Enter" ||
        e.key === "Tab"
      ) {
        e.preventDefault();
        e.stopPropagation();
        return;
      }
      if (e.key === "Escape") {
        e.preventDefault();
        e.stopPropagation();
        mentionState.value.open = false;
        return;
      }
    }

    if (e.key === "Escape") {
      e.preventDefault();
      e.stopPropagation();
      commit();
    }
  };

  const onInput = () => {
    checkMention(target);
  };

  const onKeyUp = (e: KeyboardEvent) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      checkMention(target);
    }
  };

  const onBlur = (e: FocusEvent) => {
    /* Focus moving into the merge menu or the formatting bar is still part of this edit. */
    if ((e.relatedTarget as HTMLElement)?.closest?.(".eb-mention-menu, .eb-rte")) return;
    if (mentionState.value.open) return;
    commit();
  };

  target.addEventListener("blur", onBlur);
  target.addEventListener("keydown", onKeyDown);
  target.addEventListener("input", onInput);
  target.addEventListener("keyup", onKeyUp);

  inlineCleanup = () => {
    target.removeEventListener("blur", onBlur);
    target.removeEventListener("keydown", onKeyDown);
    target.removeEventListener("input", onInput);
    target.removeEventListener("keyup", onKeyUp);
    target.contentEditable = "false";
    target.removeAttribute("data-eb-inline");
    currentTarget.value = null;
  };
}

function handleSelectMention(field: MergeField) {
  const key = definition.value?.inlineEditKey;
  const state = mentionState.value;
  const target = currentTarget.value;
  if (!state.open || !state.textNode || !target || !key) return;

  const formatted = editor.merge ? editor.merge.format(field.token) : `{{${field.token}}}`;

  const textNode = state.textNode;
  const fullText = textNode.textContent ?? "";
  const before = fullText.slice(0, state.atIndex);
  const after = fullText.slice(state.atIndex + 1 + state.query.length);
  const newText = before + formatted + " " + after;
  textNode.textContent = newText;

  // Move caret after inserted token
  const sel = window.getSelection();
  if (sel) {
    try {
      const newRange = document.createRange();
      const newOffset = Math.min(before.length + formatted.length + 1, textNode.textContent.length);
      newRange.setStart(textNode, newOffset);
      newRange.collapse(true);
      sel.removeAllRanges();
      sel.addRange(newRange);
    } catch {
      // Fallback
    }
  }

  // Save content change to editor
  const isHeading = props.block.type === "heading";
  const val = isHeading ? (target.innerText || target.textContent || "") : target.innerHTML;
  editor.updateContent(props.block.id, { [key]: val }, "inline");

  mentionState.value.open = false;
  target.focus();
}

function handleCloseMention() {
  mentionState.value.open = false;
  currentTarget.value?.focus();
}

watch(editing, (isEditing) => {
  if (inlineCleanup) {
    inlineCleanup();
    inlineCleanup = null;
  }
  if (isEditing) startInline();
});

onUnmounted(() => {
  inlineCleanup?.();
});
</script>

<template>
  <div
    v-drag="{ editor, data: { kind: 'block', blockId: block.id, columnId: column.id } }"
    v-drop="{
      editor,
      data: { kind: 'block', blockId: block.id, columnId: column.id },
      orientation: 'vertical'
    }"
    :class="classes"
    :aria-selected="selected"
    @click.stop="onClickBlock"
    @dblclick="definition?.inlineEditKey && editor.beginInlineEdit(block.id)"
  >
    <div
      v-if="isOver"
      :class="['builder-drop-indicator', edge === 'after' ? 'builder-drop-indicator--end' : '']"
    >
      <div class="builder-drop-indicator__line" />
      <span class="builder-drop-indicator__pip builder-drop-indicator__pip--left" />
      <span class="builder-drop-indicator__pill">
        <EbGlyph name="add" style="font-size: 13px; margin-right: 4px;" />
        {{ t(edge === 'after' ? 'block.dropBelow' : 'block.dropAbove') }}
      </span>
      <span class="builder-drop-indicator__pip builder-drop-indicator__pip--right" />
    </div>

    <!-- Floating Toolbar -->
    <div class="builder-block__toolbar eb-block__toolbar" data-eb-no-drag>
      <span class="builder-block__label eb-block__label">{{ definition?.label ?? block.type }}</span>

      <button
        type="button"
        class="builder-block__action eb-block__toolbar-btn eb-block__toolbar-btn--drag"
        data-eb-drag-handle
        :aria-label="t('block.move')"
        :title="t('block.move')"
      >
        <EbGlyph name="drag_indicator" />
      </button>

      <button
        type="button"
        class="builder-block__action eb-block__toolbar-btn"
        :aria-label="t('block.moveUp')"
        :disabled="blockIndex === 0"
        :title="t('block.moveUp')"
        @click.stop="moveBlock(-1)"
      >
        <EbGlyph name="arrow_upward" />
      </button>

      <button
        type="button"
        class="builder-block__action eb-block__toolbar-btn"
        :aria-label="t('block.moveDown')"
        :disabled="blockIndex >= totalBlocks - 1"
        :title="t('block.moveDown')"
        @click.stop="moveBlock(1)"
      >
        <EbGlyph name="arrow_downward" />
      </button>

      <button
        type="button"
        class="builder-block__action eb-block__toolbar-btn"
        :aria-label="t('block.duplicate')"
        :title="t('block.duplicate')"
        @click.stop="editor.duplicateBlock(block.id)"
      >
        <EbGlyph name="content_copy" />
      </button>

      <button
        type="button"
        class="builder-block__action eb-block__toolbar-btn builder-block__action--danger eb-block__toolbar-btn--danger"
        :aria-label="t('block.delete')"
        :title="t('block.delete')"
        @click.stop="editor.removeBlock(block.id)"
      >
        <EbGlyph name="delete" />
      </button>
    </div>

    <div ref="renderEl" class="eb-block__render" v-html="html" />

    <RichTextToolbar v-if="editing && richText" :host="renderEl" />

    <MentionMenu
      v-if="mentionState.open"
      :editor="editor"
      :coords="mentionState.coords"
      :query="mentionState.query"
      @select="handleSelectMention"
      @close="handleCloseMention"
    />
  </div>
</template>

// packages/react/src/components/BuilderBlock.tsx
/* ═══ BuilderBlock ═══
 *
 * A block on the canvas:
 * Floating action bar:
 *  - Label: Image, Heading, etc.
 *  - drag_indicator
 *  - arrow_upward
 *  - arrow_downward
 *  - content_copy
 *  - delete
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { Block, Column, MergeField, Row } from "@email-builder/core";
import { isRichTextField, type Editor } from "@email-builder/engine";
import { useEditor, useTranslator } from "../context";
import { useDraggable, useDroppable } from "../hooks/useDnd";
import { useEditorSelector } from "../hooks/useEditorState";
import { compileBlockPreview } from "../preview";
import { MentionMenu } from "./MentionMenu";
import { Glyph } from "./Glyph";
import { RichTextToolbar } from "./RichTextToolbar";
import { selectFromClick } from "@email-builder/engine";

export interface BuilderBlockProps {
  block: Block;
  row: Row;
  column: Column;
  columnIndex: number;
}

export function BuilderBlock({ block, row, column, columnIndex }: BuilderBlockProps) {
  const editor = useEditor();
  const t = useTranslator();
  const definition = editor.blocks.get(block.type);

  const selected = useEditorSelector(
    (state) => state.selection?.kind === "block" && (state.selection.id === block.id || state.selectedIds.includes(block.id)),
  );
  const landed = useEditorSelector((state) => state.landedId === block.id);
  const editing = useEditorSelector((state) => state.editingBlockId === block.id);
  const settings = useEditorSelector((state) => state.document.settings);

  const blockIndex = column.blocks.findIndex((b) => b.id === block.id);
  const totalBlocks = column.blocks.length;

  const moveBlock = (dir: number) => {
    const target = blockIndex + dir;
    if (target >= 0 && target < totalBlocks) {
      editor.moveBlock(block.id, column.id, target);
    }
  };

  const drop = useDroppable(
    { kind: "block", blockId: block.id, columnId: column.id },
    { orientation: "vertical" },
  );
  const drag = useDraggable({ kind: "block", blockId: block.id, columnId: column.id });

  const setNode = useCallback(
    (element: HTMLDivElement | null) => {
      drop.setNode(element);
      drag.setNode(element);
    },
    [drop.setNode, drag.setNode],
  );

  /* Re-render when the canvas switches Desktop/Mobile: mobile overrides change the preview. */
  const device = useEditorSelector((state) => state.device);
  const html = useMemo(
    () => compileBlockPreview({ editor, block, row, columnIndex }),
    [editor, block, row, columnIndex, settings, device],
  );

  const render = useRef<HTMLDivElement | null>(null);
  const { mentionState, handleSelectMention, handleCloseMention } = useInlineEdit({
    editor,
    block,
    editing,
    inlineEditKey: definition?.inlineEditKey,
    host: render,
  });

  const classes = [
    "builder-block",
    "eb-block",
    selected ? "builder-block--selected eb-block--selected" : "",
    landed ? "builder-block--landed eb-block--landed" : "",
    editing ? "builder-block--editing eb-block--editing" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      ref={setNode}
      className={classes}
      aria-selected={selected}
      onClick={(event) => {
        event.stopPropagation();
        /* ⌘/Ctrl-click and Shift-click build a multi-selection instead of starting to edit. */
        if (selectFromClick(editor, event, { kind: "block", id: block.id })) return;
        if (definition?.inlineEditKey) editor.beginInlineEdit(block.id);
      }}
      onDoubleClick={() => {
        if (definition?.inlineEditKey) editor.beginInlineEdit(block.id);
      }}
    >
      {drop.isOver && (
        <div className={`builder-drop-indicator ${drop.edge === "after" ? "builder-drop-indicator--end" : ""}`}>
          <div className="builder-drop-indicator__line" />
          <span className="builder-drop-indicator__pip builder-drop-indicator__pip--left" />
          <span className="builder-drop-indicator__pill">
            <Glyph name="add" style={{ fontSize: 13, marginRight: 4 }} />
            {t(drop.edge === "after" ? "block.dropBelow" : "block.dropAbove")}
          </span>
          <span className="builder-drop-indicator__pip builder-drop-indicator__pip--right" />
        </div>
      )}

      {/* Floating Toolbar */}
      <div className="builder-block__toolbar eb-block__toolbar" data-eb-no-drag>
        <span className="builder-block__label eb-block__label">{definition?.label ?? block.type}</span>

        <button
          type="button"
          ref={drag.setHandle}
          data-eb-drag-handle
          className="builder-block__action eb-block__toolbar-btn eb-block__toolbar-btn--drag"
          aria-label={t("block.move")}
          title={t("block.move")}
          aria-roledescription="draggable"
        >
          <Glyph name="drag_indicator" />
        </button>

        <button
          type="button"
          className="builder-block__action eb-block__toolbar-btn"
          aria-label={t("block.moveUp")}
          disabled={blockIndex === 0}
          title={t("block.moveUp")}
          onClick={(event) => {
            event.stopPropagation();
            moveBlock(-1);
          }}
        >
          <Glyph name="arrow_upward" />
        </button>

        <button
          type="button"
          className="builder-block__action eb-block__toolbar-btn"
          aria-label={t("block.moveDown")}
          disabled={blockIndex >= totalBlocks - 1}
          title={t("block.moveDown")}
          onClick={(event) => {
            event.stopPropagation();
            moveBlock(1);
          }}
        >
          <Glyph name="arrow_downward" />
        </button>

        <button
          type="button"
          className="builder-block__action eb-block__toolbar-btn"
          aria-label={t("block.duplicate")}
          title={t("block.duplicate")}
          onClick={(event) => {
            event.stopPropagation();
            editor.duplicateBlock(block.id);
          }}
        >
          <Glyph name="content_copy" />
        </button>

        <button
          type="button"
          className="builder-block__action eb-block__toolbar-btn builder-block__action--delete eb-block__toolbar-btn--danger"
          aria-label={t("block.delete")}
          title={t("block.delete")}
          onClick={(event) => {
            event.stopPropagation();
            editor.removeBlock(block.id);
          }}
        >
          <Glyph name="delete" />
        </button>
      </div>

      <div className="eb-block__render" ref={render} dangerouslySetInnerHTML={{ __html: html }} />

      {/* Formatting bar — only for rich-text fields; headings and labels are stored as plain text. */}
      {editing && isRichTextField(definition, definition?.inlineEditKey) && <RichTextToolbar host={render} />}

      {mentionState.open && (
        <MentionMenu
          editor={editor}
          coords={mentionState.coords}
          query={mentionState.query}
          onSelect={handleSelectMention}
          onClose={handleCloseMention}
        />
      )}
    </div>
  );
}

/* ── Inline editing ── */
interface InlineEditInput {
  editor: Editor;
  block: Block;
  editing: boolean;
  inlineEditKey: string | undefined;
  host: { current: HTMLElement | null };
}

interface MentionState {
  open: boolean;
  coords: { top: number; left: number };
  query: string;
  atIndex: number;
  textNode: Node | null;
}

function useInlineEdit({ editor, block, editing, inlineEditKey, host }: InlineEditInput) {
  const [mentionState, setMentionState] = useState<MentionState>({
    open: false,
    coords: { top: 0, left: 0 },
    query: "",
    atIndex: -1,
    textNode: null,
  });

  const mentionStateRef = useRef(mentionState);
  mentionStateRef.current = mentionState;

  const targetRef = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!editing || !inlineEditKey) return;
    const target = resolveInlineTarget(host.current);
    if (!target) {
      editor.endInlineEdit();
      return;
    }
    targetRef.current = target;

    target.setAttribute("data-eb-inline", "");
    target.contentEditable = "true";

    // Focus immediately if not already focused
    if (document.activeElement !== target) {
      target.focus();
    }

    const checkMention = () => {
      const sel = window.getSelection();
      if (!sel || !sel.rangeCount || !sel.isCollapsed) {
        setMentionState((prev) => (prev.open ? { ...prev, open: false } : prev));
        return;
      }
      const range = sel.getRangeAt(0);
      const node = range.startContainer;
      if (node.nodeType !== Node.TEXT_NODE) {
        setMentionState((prev) => (prev.open ? { ...prev, open: false } : prev));
        return;
      }

      const text = node.textContent ?? "";
      const offset = range.startOffset;
      const textBefore = text.slice(0, offset);
      const atIndex = textBefore.lastIndexOf("@");
      if (atIndex === -1) {
        setMentionState((prev) => (prev.open ? { ...prev, open: false } : prev));
        return;
      }

      const query = textBefore.slice(atIndex + 1);
      if (/[\s\n\r]/.test(query)) {
        setMentionState((prev) => (prev.open ? { ...prev, open: false } : prev));
        return;
      }

      let coords = { top: 0, left: 0 };
      try {
        const cloneRange = range.cloneRange();
        cloneRange.setStart(node, atIndex);
        cloneRange.setEnd(node, offset);
        const rect = cloneRange.getBoundingClientRect();
        if (rect && rect.top > 0) {
          coords = { top: rect.bottom, left: rect.left };
        } else {
          const tRect = target.getBoundingClientRect();
          coords = { top: tRect.bottom, left: tRect.left + 20 };
        }
      } catch {
        const tRect = target.getBoundingClientRect();
        coords = { top: tRect.bottom, left: tRect.left + 20 };
      }

      setMentionState({
        open: true,
        coords,
        query,
        atIndex,
        textNode: node,
      });
    };

    const commit = () => {
      const isHeading = block.type === "heading";
      const val = isHeading ? (target.innerText || target.textContent || "") : target.innerHTML;
      editor.updateContent(block.id, { [inlineEditKey]: val }, "inline");
      editor.endInlineEdit();
    };

    const onKeyDown = (event: KeyboardEvent) => {
      if (mentionStateRef.current.open) {
        if (
          event.key === "ArrowDown" ||
          event.key === "ArrowUp" ||
          event.key === "Enter" ||
          event.key === "Tab"
        ) {
          event.preventDefault();
          event.stopPropagation();
          return;
        }
        if (event.key === "Escape") {
          event.preventDefault();
          event.stopPropagation();
          setMentionState((prev) => ({ ...prev, open: false }));
          return;
        }
      }

      if (event.key === "Escape") {
        event.preventDefault();
        event.stopPropagation();
        commit();
      }
    };

    const onInput = () => {
      checkMention();
    };

    const onKeyUp = (e: KeyboardEvent) => {
      if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
        checkMention();
      }
    };

    const onBlur = (event: FocusEvent) => {
      /* Focus moving into the merge menu or the formatting bar is still part of this edit. */
      if ((event.relatedTarget as HTMLElement)?.closest?.(".eb-mention-menu, .eb-rte")) return;
      if (mentionStateRef.current.open) return;
      commit();
    };

    target.addEventListener("blur", onBlur);
    target.addEventListener("keydown", onKeyDown);
    target.addEventListener("input", onInput);
    target.addEventListener("keyup", onKeyUp);

    return () => {
      target.removeEventListener("blur", onBlur);
      target.removeEventListener("keydown", onKeyDown);
      target.removeEventListener("input", onInput);
      target.removeEventListener("keyup", onKeyUp);
      target.contentEditable = "false";
      target.removeAttribute("data-eb-inline");
    };
  }, [editor, block.id, block.type, editing, inlineEditKey, host]);

  const handleSelectMention = (field: MergeField) => {
    const state = mentionStateRef.current;
    const target = targetRef.current;
    if (!state.open || !state.textNode || !target || !inlineEditKey) return;

    const formatted = editor.merge ? editor.merge.format(field.token) : `{{${field.token}}}`;

    const textNode = state.textNode;
    const fullText = textNode.textContent ?? "";
    const before = fullText.slice(0, state.atIndex);
    const after = fullText.slice(state.atIndex + 1 + state.query.length);
    const newText = before + formatted + " " + after;
    textNode.textContent = newText;

    // Move caret after inserted token
    const sel = window.getSelection();
    if (sel) {
      try {
        const newRange = document.createRange();
        const newOffset = Math.min(before.length + formatted.length + 1, textNode.textContent.length);
        newRange.setStart(textNode, newOffset);
        newRange.collapse(true);
        sel.removeAllRanges();
        sel.addRange(newRange);
      } catch {
        // Fallback
      }
    }

    // Save content change to editor
    const isHeading = block.type === "heading";
    const val = isHeading ? (target.innerText || target.textContent || "") : target.innerHTML;
    editor.updateContent(block.id, { [inlineEditKey]: val }, "inline");

    setMentionState((prev) => ({ ...prev, open: false }));
    target.focus();
  };

  const handleCloseMention = () => {
    setMentionState((prev) => ({ ...prev, open: false }));
    targetRef.current?.focus();
  };

  return {
    mentionState,
    handleSelectMention,
    handleCloseMention,
  };
}

function resolveInlineTarget(host: HTMLElement | null): HTMLElement | null {
  if (!host) return null;
  const marked = host.querySelector<HTMLElement>("[data-eb-inline]");
  if (marked) return marked;
  const cell = host.querySelector("td");
  const first = cell?.firstElementChild;
  return first instanceof HTMLElement ? first : null;
}
