// packages/react/src/components/BuilderField.tsx
/* ═══ BuilderField ═══
 *
 * One declarative field from a block's schema. Every `Field["kind"]` is handled here, which is
 * what lets a host's custom block get controls identical to a built-in's without writing UI.
 *
 * The markup per kind is dictated by `packages/styles/src/fields.css` — the class names are the
 * spec, and nothing here invents one. */

import { useId, useRef, type ReactNode } from "react";
import { FONT_STACKS, type Border, type FieldOption, type Padding } from "@email-builder/core";
import { useEditor, useTranslator } from "../context";
import { AlignCenterIcon, AlignLeftIcon, AlignRightIcon } from "../icons";
import { asBoolean, asNumber, asString, type BuilderFieldProps, type CustomWidgetProps } from "../types";
import { BorderControl } from "./fields/BorderField";
import { ColorControl } from "./fields/ColorField";
import { ImageControl } from "./fields/ImageField";
import { ListControl } from "./fields/ListField";
import { MergeTrigger } from "./fields/MergeMenu";
import { PaddingControl } from "./fields/PaddingField";
import { RecordControl } from "./fields/RecordField";
import { RichTextControl } from "./fields/RichTextField";

const ALIGN_ICONS = {
  left: AlignLeftIcon,
  center: AlignCenterIcon,
  right: AlignRightIcon,
} as const;

export function BuilderField({ field, value, onChange, block }: BuilderFieldProps) {
  const id = useId();
  /* Held so the merge picker can insert at the caret of whatever control this field rendered. */
  const control = useRef<HTMLElement | null>(null);
  const label = field.label ?? field.key;
  const mergeable = "mergeable" in field && field.mergeable === true;

  /* The toggle carries its own label inside `.eb-toggle`, so a second one above it would read as
     two separate controls. */
  const showLabel = field.kind !== "toggle";

  return (
    <div className="eb-field">
      {showLabel ? (
        <label className="eb-field__label" htmlFor={id}>
          <span>{label}</span>
          {mergeable ? (
            <MergeTrigger control={control} value={asString(value)} onChange={onChange} />
          ) : null}
        </label>
      ) : null}

      <Control
        field={field}
        value={value}
        onChange={onChange}
        block={block}
        id={id}
        label={label}
        control={control}
      />

      {field.help ? <span className="eb-field__help">{field.help}</span> : null}
    </div>
  );
}

interface ControlProps extends BuilderFieldProps {
  id: string;
  label: string;
  control: { current: HTMLElement | null };
}

function Control({ field, value, onChange, block, id, label, control }: ControlProps): ReactNode {
  const editor = useEditor();
  const t = useTranslator();

  switch (field.kind) {
    /* ── Text-like ── */
    case "text":
    case "url":
      return (
        <input
          id={id}
          ref={(element) => {
            control.current = element;
          }}
          className="eb-input"
          type={field.kind === "url" ? "url" : "text"}
          value={asString(value)}
          maxLength={field.kind === "text" ? field.maxLength : undefined}
          placeholder={field.placeholder}
          onChange={(event) => onChange(event.target.value)}
        />
      );

    case "textarea":
      return (
        <textarea
          id={id}
          ref={(element) => {
            control.current = element;
          }}
          /* `--code` for an HTML block: proportional type makes markup unreadable. */
          className={`eb-textarea${field.key === "html" ? " eb-textarea--code" : ""}`}
          rows={field.rows}
          value={asString(value)}
          placeholder={field.placeholder}
          onChange={(event) => onChange(event.target.value)}
        />
      );

    case "richtext":
      return (
        <RichTextControl
          value={value}
          label={label}
          placeholder={field.placeholder}
          onChange={onChange}
        />
      );

    /* ── Numeric ── */
    case "number":
      return (
        <div className="eb-number">
          <input
            id={id}
            className="eb-input"
            type="number"
            min={field.min}
            max={field.max}
            step={field.step}
            value={asString(value)}
            onChange={(event) =>
              onChange(event.target.value === "" ? undefined : asNumber(event.target.value))
            }
          />
          {field.suffix ? <span className="eb-number__suffix">{field.suffix}</span> : null}
        </div>
      );

    case "range":
      return (
        <div className="eb-range">
          <input
            id={id}
            className="eb-range__input"
            type="range"
            min={field.min}
            max={field.max}
            step={field.step ?? 1}
            value={asNumber(value, field.min)}
            onChange={(event) => onChange(asNumber(event.target.value, field.min))}
          />
          <span className="eb-range__value">
            {asNumber(value, field.min)}
            {field.suffix}
          </span>
        </div>
      );

    /* ── Colour, toggle, choice ── */
    case "color":
      return (
        <ColorControl
          value={value}
          label={label}
          allowTransparent={field.allowTransparent}
          onChange={onChange}
        />
      );

    case "toggle":
      return (
        <label className="eb-toggle">
          <span>{label}</span>
          <input
            id={id}
            type="checkbox"
            checked={asBoolean(value)}
            onChange={(event) => onChange(event.target.checked)}
          />
          <span className="eb-toggle__track">
            <span className="eb-toggle__thumb" />
          </span>
        </label>
      );

    /* A native select, deliberately: the one control that is fully accessible and fully native on
       mobile without a library. */
    case "select":
      return (
        <select
          id={id}
          className="eb-select"
          value={asString(value)}
          onChange={(event) => onChange(decodeOption(field.options, event.target.value))}
        >
          {field.options.map((option) => (
            <option key={String(option.value)} value={String(option.value)}>
              {option.label}
            </option>
          ))}
        </select>
      );

    case "segmented":
      return (
        <div className="eb-segmented inspector-segmented" role="group" aria-label={label}>
          {field.options.map((option) => {
            const isSelected = asString(value) === String(option.value);
            return (
              <button
                key={String(option.value)}
                type="button"
                className={`eb-segmented__item inspector-segmented__option${isSelected ? " eb-segmented__item--active inspector-segmented__option--active" : ""}`}
                aria-pressed={isSelected}
                onClick={() => onChange(option.value)}
              >
                {option.label}
              </button>
            );
          })}
        </div>
      );

    case "align":
      return (
        <div className="eb-align" role="group" aria-label={label}>
          {(["left", "center", "right"] as const).map((alignment) => {
            const Icon = ALIGN_ICONS[alignment];
            return (
              <button
                key={alignment}
                type="button"
                className="eb-align__btn"
                aria-pressed={asString(value) === alignment}
                aria-label={t(`field.align.${alignment}`, alignment)}
                onClick={() => onChange(alignment)}
              >
                <Icon />
              </button>
            );
          })}
        </div>
      );

    case "font":
      return (
        <select
          id={id}
          className="eb-select"
          value={asString(value)}
          onChange={(event) => onChange(event.target.value)}
        >
          {FONT_STACKS.map((stack) => (
            <option key={stack.value} value={stack.value}>
              {stack.label}
            </option>
          ))}
        </select>
      );

    /* ── Composite ── */
    case "padding":
      return <PaddingControl value={value} onChange={onChange as (value: Padding) => void} />;

    case "border":
      return (
        <BorderControl value={value} label={label} onChange={onChange as (value: Border) => void} />
      );

    case "image":
      return <ImageControl value={value} fieldKey={field.key} block={block} onChange={onChange} />;

    case "list":
      return <ListControl field={field} value={value} block={block} onChange={onChange} />;

    case "record":
      return <RecordControl field={field} value={value} block={block} onChange={onChange} />;

    /* ── Host escape hatch ── */
    case "custom": {
      const Widget = editor.adapter.widgets?.[field.widget] as
        | ((props: CustomWidgetProps) => ReactNode)
        | undefined;
      if (!Widget) return null;
      return <Widget field={field} value={value} onChange={onChange} block={block} editor={editor} />;
    }

    default:
      return null;
  }
}

/** `FieldOption.value` may be a number or a boolean; a `<select>` only ever gives back a string. */
function decodeOption(options: FieldOption[], raw: string): unknown {
  const match = options.find((option) => String(option.value) === raw);
  return match ? match.value : raw;
}

// packages/vue/src/components/BuilderField.vue
<script setup lang="ts">
/* ═══ BuilderField ═══
 *
 * One `Field` from a block's declarative schema, rendered. Every kind lives here so that a host
 * block and a built-in block get identical controls without either of them writing a line of UI.
 *
 * Union members are read through small computed accessors rather than narrowed in the template:
 * the template compiler's narrowing does not survive nesting, and a cast per binding is worse than
 * one accessor per property.
 *
 * The contract's `onChange` is the `change` event here — that is the same thing in Vue, and a
 * function prop of that name would fire twice for a parent that also listens. */

import { computed, nextTick, onMounted, ref, watch, type Component } from "vue";
import {
  ALIGN_OPTIONS,
  FONT_STACKS,
  type Block,
  type Border,
  type Field,
  type FieldOption,
  type Padding,
} from "@email-builder/core";
import { useEditor, useTranslator } from "../context";
import { UI_ICONS } from "../icons";
import { nextId } from "../util";
import EbIcon from "./EbIcon.vue";
import BorderControl from "./fields/BorderControl.vue";
import ColorControl from "./fields/ColorControl.vue";
import ImageControl from "./fields/ImageControl.vue";
import ListControl from "./fields/ListControl.vue";
import MergeMenu from "./fields/MergeMenu.vue";
import PaddingControl from "./fields/PaddingControl.vue";
import RecordControl from "./fields/RecordControl.vue";

const props = defineProps<{ field: Field; value: unknown; block?: Block | null }>();
const emit = defineEmits<{
  change: [value: unknown];
  /** A record pick fills several content keys at once. */
  patch: [changes: Record<string, unknown>];
}>();

const editor = useEditor();
const t = useTranslator(editor);

/* Per-instance id, so a <label for> reaches its own control and not the same key in another
   panel. Generated once in setup rather than in render, which would break the association on
   every re-render. */
const uid = `eb-field-${nextId()}`;

const control = ref<HTMLInputElement | HTMLTextAreaElement | null>(null);
const rich = ref<HTMLElement | null>(null);

/* ─── Field shape ─── */

const kind = computed(() => props.field.kind);
const label = computed(() => props.field.label ?? props.field.key);
const text = computed(() => (props.value === undefined || props.value === null ? "" : String(props.value)));
const numeric = computed(() => (typeof props.value === "number" ? props.value : Number(props.value) || 0));
const options = computed<FieldOption[]>(() => ("options" in props.field ? props.field.options : []));
const placeholder = computed(() => ("placeholder" in props.field ? props.field.placeholder : undefined));
const suffix = computed(() => ("suffix" in props.field ? props.field.suffix : undefined));
const min = computed(() => ("min" in props.field ? props.field.min : undefined));
const max = computed(() => ("max" in props.field ? props.field.max : undefined));
const step = computed(() => ("step" in props.field ? props.field.step : undefined));
const rows = computed(() => ("rows" in props.field ? props.field.rows : undefined));
const maxLength = computed(() => ("maxLength" in props.field ? props.field.maxLength : undefined));
const allowTransparent = computed(() => ("allowTransparent" in props.field ? props.field.allowTransparent : false));
const listField = computed(() => props.field as Extract<Field, { kind: "list" }>);
const recordField = computed(() => props.field as Extract<Field, { kind: "record" }>);

const mergeable = computed(() => !!editor.merge && "mergeable" in props.field && props.field.mergeable === true);
const showLabel = computed(() => kind.value !== "toggle");

/** A `when` guard is the field's own business — a host that renders one directly gets it too. */
const visible = computed(() => {
  const guard = props.field.when;
  if (!guard) return true;
  return guard(props.value, (props.block ?? { id: "", type: "", content: {}, style: {} }) as Block, editor.getDocument());
});

/* A host widget is whatever the view layer understands — here, a Vue component. */
const widget = computed<Component | null>(() =>
  props.field.kind === "custom" ? ((editor.adapter.widgets?.[props.field.widget] as Component) ?? null) : null,
);
const widgetProps = computed(() => (props.field.kind === "custom" ? (props.field.props ?? {}) : {}));

/* ─── Writes ─── */

const change = (next: unknown) => emit("change", next);

const onSelect = (event: Event) => {
  const raw = (event.target as HTMLSelectElement).value;
  /* Options may be numbers or booleans; hand back the option's own value, not the DOM string. */
  const picked = options.value.find((option) => String(option.value) === raw);
  change(picked ? picked.value : raw);
};

const alignIcon = (value: unknown) =>
  value === "center" ? UI_ICONS.alignCenter : value === "right" ? UI_ICONS.alignRight : UI_ICONS.alignLeft;

/* ─── Rich text ───
 *
 * A contenteditable cannot be a controlled value: writing innerHTML back while the caret is in it
 * moves the caret to the start. So it is written on mount and whenever the value changes from
 * elsewhere — never while it has focus. */

const paint = () => {
  const element = rich.value;
  if (!element) return;
  if (document.activeElement === element) return;
  const next = text.value;
  if (element.innerHTML !== next) element.innerHTML = next;
};

onMounted(paint);
watch(text, paint);
watch(rich, paint);

/* ─── Merge tokens ─── */

function insertToken(token: string) {
  const input = control.value;
  if (input && document.activeElement === input) {
    const start = input.selectionStart ?? input.value.length;
    const end = input.selectionEnd ?? start;
    change(input.value.slice(0, start) + token + input.value.slice(end));
    void nextTick(() => {
      input.focus();
      const caret = start + token.length;
      input.setSelectionRange(caret, caret);
    });
    return;
  }

  const editable = rich.value;
  if (editable) {
    const selection = window.getSelection();
    const range = selection && selection.rangeCount ? selection.getRangeAt(0) : null;
    if (range && editable.contains(range.commonAncestorContainer)) {
      range.deleteContents();
      range.insertNode(document.createTextNode(token));
      range.collapse(false);
      change(editable.innerHTML);
      return;
    }
    editable.innerHTML = text.value + token;
    change(editable.innerHTML);
    return;
  }

  /* Not focused, so there is no caret to respect — append. */
  change(text.value + token);
}
</script>

<template>
  <div v-if="visible" class="eb-field">
    <label v-if="showLabel" class="eb-field__label" :for="uid">
      <span>{{ label }}</span>
      <MergeMenu v-if="mergeable" @insert="insertToken" />
    </label>

    <!-- text / url -->
    <input
      v-if="kind === 'text' || kind === 'url'"
      :id="uid"
      ref="control"
      :type="kind === 'url' ? 'url' : 'text'"
      class="eb-input"
      :placeholder="placeholder"
      :maxlength="maxLength"
      :value="text"
      @input="change(($event.target as HTMLInputElement).value)"
    />

    <!-- textarea -->
    <textarea
      v-else-if="kind === 'textarea'"
      :id="uid"
      ref="control"
      class="eb-textarea"
      :class="{ 'eb-textarea--code': props.field.key === 'html' }"
      :rows="rows ?? 4"
      :placeholder="placeholder"
      :value="text"
      @input="change(($event.target as HTMLTextAreaElement).value)"
    />

    <!-- richtext -->
    <div
      v-else-if="kind === 'richtext'"
      :id="uid"
      ref="rich"
      class="eb-textarea"
      contenteditable="true"
      role="textbox"
      aria-multiline="true"
      :aria-label="label"
      @input="change(($event.target as HTMLElement).innerHTML)"
      @blur="change(($event.target as HTMLElement).innerHTML)"
    />

    <!-- number -->
    <div v-else-if="kind === 'number'" class="eb-number">
      <input
        :id="uid"
        type="number"
        class="eb-input"
        :min="min"
        :max="max"
        :step="step"
        :value="numeric"
        @input="change(Number(($event.target as HTMLInputElement).value))"
      />
      <span v-if="suffix" class="eb-number__suffix">{{ suffix }}</span>
    </div>

    <!-- range -->
    <div v-else-if="kind === 'range'" class="eb-range">
      <input
        :id="uid"
        type="range"
        class="eb-range__input"
        :min="min"
        :max="max"
        :step="step ?? 1"
        :value="numeric"
        @input="change(Number(($event.target as HTMLInputElement).value))"
      />
      <span class="eb-range__value">{{ numeric }}{{ suffix ?? "" }}</span>
    </div>

    <!-- color -->
    <ColorControl
      v-else-if="kind === 'color'"
      :value="text"
      :label="label"
      :allow-transparent="allowTransparent"
      @change="change($event)"
    />

    <!-- toggle -->
    <label v-else-if="kind === 'toggle'" class="eb-toggle">
      <span>{{ label }}</span>
      <input
        type="checkbox"
        :checked="props.value === true"
        @change="change(($event.target as HTMLInputElement).checked)"
      />
      <span class="eb-toggle__track"><span class="eb-toggle__thumb" /></span>
    </label>

    <!-- select -->
    <select v-else-if="kind === 'select'" :id="uid" class="eb-select" :value="text" @change="onSelect">
      <option v-for="option in options" :key="String(option.value)" :value="String(option.value)">
        {{ option.label }}
      </option>
    </select>

    <!-- font -->
    <select v-else-if="kind === 'font'" :id="uid" class="eb-select" :value="text" @change="change(($event.target as HTMLSelectElement).value)">
      <option value="">{{ t("field.themeFont", "Theme font") }}</option>
      <option v-for="stack in FONT_STACKS" :key="stack.value" :value="stack.value">{{ stack.label }}</option>
    </select>

    <!-- segmented -->
    <div v-else-if="kind === 'segmented'" class="eb-segmented inspector-segmented" role="group" :aria-label="label">
      <button
        v-for="option in options"
        :key="String(option.value)"
        type="button"
        class="eb-segmented__item inspector-segmented__option"
        :class="{ 'eb-segmented__item--active inspector-segmented__option--active': String(option.value) === text }"
        :aria-pressed="String(option.value) === text"
        @click="change(option.value)"
      >
        {{ option.label }}
      </button>
    </div>

    <!-- align -->
    <div v-else-if="kind === 'align'" class="eb-align" role="group" :aria-label="label">
      <button
        v-for="option in ALIGN_OPTIONS"
        :key="option.value"
        type="button"
        class="eb-align__btn"
        :aria-pressed="option.value === text"
        :aria-label="option.label"
        :title="option.label"
        @click="change(option.value)"
      >
        <EbIcon :svg="alignIcon(option.value)" />
      </button>
    </div>

    <!-- padding -->
    <PaddingControl
      v-else-if="kind === 'padding'"
      :value="props.value as Padding | undefined"
      :label="label"
      @change="change($event)"
    />

    <!-- border -->
    <BorderControl
      v-else-if="kind === 'border'"
      :value="props.value as Border | undefined"
      :label="label"
      @change="change($event)"
    />

    <!-- image -->
    <ImageControl
      v-else-if="kind === 'image'"
      :value="text"
      :label="label"
      :context-id="props.block?.id ?? ''"
      :field-key="props.field.key"
      @change="change($event)"
    />

    <!-- list -->
    <ListControl v-else-if="kind === 'list'" :field="listField" :value="props.value" @change="change($event)">
      <template #field="item">
        <BuilderField :field="item.field" :value="item.value" :block="props.block" @change="item.update($event)" />
      </template>
    </ListControl>

    <!-- record -->
    <RecordControl v-else-if="kind === 'record'" :field="recordField" @patch="emit('patch', $event)" />

    <!-- custom -->
    <component
      v-else-if="kind === 'custom' && widget"
      :is="widget"
      v-bind="widgetProps"
      :field="props.field"
      :value="props.value"
      :block="props.block"
      :editor="editor"
      :on-change="change"
      @change="change($event)"
    />
    <p v-else-if="kind === 'custom'" class="eb-field__help">
      {{ t("field.missingWidget", "No widget registered for this field.") }}
    </p>

    <p v-if="props.field.help" class="eb-field__help">{{ props.field.help }}</p>
  </div>
</template>
