// packages/react/src/components/BuilderColumn.tsx
/* ═══ BuilderColumn ═══
 *
 * A drop container, not a drop seam: dropping onto a column appends to it, while dropping onto a
 * block inside it inserts at that block's edge. The engine's `container: true` is what encodes
 * that difference. */

import { useMemo } from "react";
import { columnWidths, type Column, type Row } from "@email-builder/core";
import { columnCanvasStyle } from "@email-builder/engine";
import { useEditor, useTranslator } from "../context";
import { useDroppable } from "../hooks/useDnd";
import { useEditorSelector } from "../hooks/useEditorState";
import { PlusIcon } from "../icons";
import { BuilderBlock } from "./BuilderBlock";

export interface BuilderColumnProps {
  row: Row;
  column: Column;
  columnIndex: number;
}

export function BuilderColumn({ row, column, columnIndex }: BuilderColumnProps) {
  const editor = useEditor();
  const t = useTranslator();
  const selected = useEditorSelector(
    (state) => state.selection?.kind === "column" && state.selection.id === column.id,
  );
  const contentWidth = useEditorSelector((state) => state.document.settings.contentWidth);

  const drop = useDroppable(
    { kind: "column", columnId: column.id, rowId: row.id },
    { container: true },
  );

  /* Percentages rather than the px widths core emits: the sheet narrows to 375px in mobile
     preview, and the columns have to narrow with it. */
  const basis = useMemo(() => {
    const widths = columnWidths(row, contentWidth);
    const total = widths.reduce((sum, width) => sum + width, 0) || 1;
    return `${((widths[columnIndex] ?? total) / total) * 100}%`;
  }, [row, contentWidth, columnIndex]);

  const empty = column.blocks.length === 0;
  const classes = [
    "eb-column",
    empty ? "eb-column--empty" : "",
    selected ? "eb-column--selected" : "",
    drop.isOver ? "eb-column--over" : "",
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <div
      ref={drop.setNode}
      className={classes}
      style={{ flex: `0 0 ${basis}`, maxWidth: basis, ...columnCanvasStyle(column.style) }}
      onClick={(event) => {
        event.stopPropagation();
        editor.select({ kind: "column", id: column.id });
      }}
    >
      {empty ? (
        <div className={`eb-dropzone${drop.isOver ? " eb-dropzone--over" : ""}`}>
          <span className="eb-dropzone__icon">
            <PlusIcon />
          </span>
          <span className="eb-dropzone__labels">
            <span className="eb-dropzone__label eb-dropzone__label--idle">{t("canvas.emptyColumn")}</span>
            <span className="eb-dropzone__label eb-dropzone__label--over" aria-hidden="true">
              {t("canvas.dropRelease")}
            </span>
          </span>
        </div>
      ) : (
        column.blocks.map((block) => (
          <BuilderBlock
            key={block.id}
            block={block}
            row={row}
            column={column}
            columnIndex={columnIndex}
          />
        ))
      )}
    </div>
  );
}

// packages/vue/src/components/BuilderColumn.vue
<script setup lang="ts">
/* ═══ BuilderColumn ═══
 *
 * A droppable container. Columns take flex-basis from their fractional weight relative to the
 * row total so they narrow correctly in mobile preview. */

import { computed } from "vue";
import { columnWidths, type Column, type Row } from "@email-builder/core";
import { columnCanvasStyle } from "@email-builder/engine";
import { useEditor, useTranslator } from "../context";
import { useDragState, useEditorSelector } from "../composables";
import { vDrop } from "../directives";
import { UI_ICONS } from "../icons";
import BuilderBlock from "./BuilderBlock.vue";
import EbIcon from "./EbIcon.vue";

const props = defineProps<{ row: Row; column: Column; columnIndex: number }>();

const editor = useEditor();
const t = useTranslator(editor);

const selected = useEditorSelector(
  (state) => state.selection?.kind === "column" && state.selection.id === props.column.id,
);
const contentWidth = useEditorSelector((state) => state.document.settings.contentWidth);

/* Percentage flex-basis so the columns shrink together in mobile preview. */
const basis = computed(() => {
  const widths = columnWidths(props.row, contentWidth.value);
  const total = widths.reduce((s, w) => s + w, 0) || 1;
  return `${((widths[props.columnIndex] ?? total) / total) * 100}%`;
});

const empty = computed(() => props.column.blocks.length === 0);

const dragState = useDragState();

/* Track isOver via the engine's dnd state (DragState), not EditorState */
const isOver = computed(() => {
  const ds = dragState.value;
  return !!ds.active && ds.over?.kind === "column" && (ds.over as any).columnId === props.column.id;
});

const classes = computed(() =>
  [
    "eb-column",
    empty.value ? "eb-column--empty" : "",
    selected.value ? "eb-column--selected" : "",
    isOver.value ? "eb-column--over" : "",
  ]
    .filter(Boolean)
    .join(" "),
);
</script>

<template>
  <div
    v-drop="{
      editor,
      data: { kind: 'column', columnId: column.id, rowId: row.id },
      container: true
    }"
    :class="classes"
    :style="{ flex: `0 0 ${basis}`, maxWidth: basis, ...columnCanvasStyle(column.style) }"
    @click.stop="editor.select({ kind: 'column', id: column.id })"
  >
    <div v-if="empty" :class="['eb-dropzone', isOver ? 'eb-dropzone--over' : '']">
      <span class="eb-dropzone__icon"><EbIcon :svg="UI_ICONS.plus" /></span>
      <span class="eb-dropzone__labels">
        <span class="eb-dropzone__label eb-dropzone__label--idle">{{ t("canvas.emptyColumn") }}</span>
        <span class="eb-dropzone__label eb-dropzone__label--over" aria-hidden="true">{{ t("canvas.dropRelease") }}</span>
      </span>
    </div>
    <BuilderBlock
      v-for="(block, bi) in column.blocks"
      :key="block.id"
      :block="block"
      :row="row"
      :column="column"
      :column-index="columnIndex"
    />
  </div>
</template>
